# Generated by Django 3.0.5 on 2020-11-09 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=1000)),
                ('serviceCharge', models.IntegerField(default=50)),
                ('businessDescription', models.TextField(default='Business Default Description')),
                ('userModel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=1000)),
                ('userModel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentStatus', models.BooleanField(default=False)),
                ('deliveryStatus', models.BooleanField(default=False)),
                ('totalAmount', models.IntegerField(default=0)),
                ('businessModelLink', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='customer_block.BusinessModel')),
                ('productModelLink', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='image_model.Product')),
                ('userModelLink', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='customer_block.CustomerModel')),
            ],
        ),
    ]
