# Generated by Django 3.0.5 on 2020-11-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_model', '0002_auto_20201109_1702'),
        ('customer_block', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='businessModelLink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer_block.BusinessModel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='productModelLink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='image_model.Product'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='userModelLink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer_block.CustomerModel'),
        ),
    ]
