# Generated by Django 3.0.5 on 2020-11-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductUrl',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
